<?php

use Illuminate\Database\Seeder;

class DelegatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("delegates")->insert([
            ["id"=>"I01-099", "name"=>"Bùi Trung Tín", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I02-100", "name"=>"Đào Hữu Duy Quân", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I03-101", "name"=>"Nguyễn Cường Phát", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I04-102", "name"=>"Bùi Trọng Khánh Duy", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I05-103", "name"=>"Đoàn Công Minh", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I06-104", "name"=>"Hồ Trần Thiện Đạt", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I07-105", "name"=>"Lê Thị Hà", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I08-106", "name"=>"Lương Kim Phượng", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J01-107", "name"=>"Nguyễn Cao Việt Hòa", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J02-108", "name"=>"Nguyễn Du Phúc Ngân", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J03-109", "name"=>"Nguyễn Kỷ Nguyên", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J04-110", "name"=>"Nguyễn Lê Thành", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J05-111", "name"=>"Nguyễn Phạm Đức Duy", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J06-112", "name"=>"Nguyễn Thành Trung", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J07-113", "name"=>"Nguyễn Yến Nhi", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J08-114", "name"=>"Tạ Quang Tiến", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K01-115", "name"=>"Thái Thị Phương Lan", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K02-116", "name"=>"Trần Ngọc Toàn", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K03-117", "name"=>"Võ Thành Trung", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K04-118", "name"=>"Vũ Tuấn Hải", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K05-119", "name"=>"Dương Vũ Hoàng Hiệp", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"K06-120", "name"=>"Hoàng Đình Quang", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"K07-121", "name"=>"Nguyễn Tài Nguyên", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"K08-122", "name"=>"Nguyễn Thanh Tuấn", "faculty"=>"Khoa Công nghệ Phần mềm", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"B09-030", "name"=>"Nguyễn Đặng Mỹ Ngọc", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"B10-031", "name"=>"Nguyễn Minh Đức", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"B11-032", "name"=>"Đỗ Hoàng Hiệp", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B12-033", "name"=>"Đỗ Ngọc Dũng", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B14-034", "name"=>"Huỳnh Đức Huy", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B15-035", "name"=>"Hỷ Hoa Phương", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C9-036", "name"=>"Lê Hồng Minh", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C10-037", "name"=>"Lê Thị Mỹ Diệu", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C11-038", "name"=>"Lê Thị Trúc Hòa", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C12-039", "name"=>"Lê Võ Đình Kha", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C13-040", "name"=>"Lưu Gia Mẫn", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C14-041", "name"=>"Nguyễn Bích Trâm", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C15-042", "name"=>"Nguyễn Hồng Phương", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D09-043", "name"=>"Nguyễn Hữu Phước", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D10-044", "name"=>"Nguyễn Huỳnh Như Thảo", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D11-045", "name"=>"Nguyễn Thị Huỳnh Thi", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D12-046", "name"=>"Nguyễn Thị Thục Trinh", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D13-047", "name"=>"Phan Thị Lê Na", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D14-048", "name"=>"Phan Thùy Dương", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D15-049", "name"=>"Phùng Mỹ Liên", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D16-050", "name"=>"Trần Hữu Phát", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"E09-051", "name"=>"Trần Quốc Anh", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"E10-052", "name"=>"Trương Minh Thiện", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"E11-053", "name"=>"Lê Minh Đức", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E12-054", "name"=>"Lê Nguyễn Thảo Duyên", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E13-055", "name"=>"Trương Minh Dương", "faculty"=>"Khoa Hệ thống Thông tin", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"F01-056", "name"=>"Nguyễn Minh Nghĩa", "faculty"=>"Cán bộ trẻ", "group"=> 2, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F02-057", "name"=>"Nguyễn Nhật Bằng", "faculty"=>"Cán bộ trẻ", "group"=> 2, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F03-058", "name"=>"Nguyễn Thành Hiệp", "faculty"=>"Cán bộ trẻ", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F04-059", "name"=>"Vũ Khánh", "faculty"=>"Cán bộ trẻ", "group"=> 3, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F05-060", "name"=>"Lê Thị Phương", "faculty"=>"Cán bộ trẻ", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"F06-061", "name"=>"Phan Trường Nhất", "faculty"=>"Cán bộ trẻ", "group"=> 2, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"F07-062", "name"=>"Bùi Minh Hiếu", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F08-063", "name"=>"Hồ Thị Trang", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"G01-064", "name"=>"Nguyễn Thành Luân", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"G02-065", "name"=>"Hồ Thị Trang", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G03-066", "name"=>"Huỳnh Phan Minh Quang", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G04-067", "name"=>"Nguyễn Bá Quốc", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G05-068", "name"=>"Nguyễn Đình Quốc Bảo", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G06-069", "name"=>"Nguyễn Lê Thanh Phụng", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G07-070", "name"=>"Nguyễn Thế Thiện", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G08-071", "name"=>"Nguyễn Thị Bích Diễm", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H01-072", "name"=>"Nguyễn Thị Hồng Nhung", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H02-073", "name"=>"Phạm Đình Việt", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H03-074", "name"=>"Phan Thị Kim Chi", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H04-075", "name"=>"Tạ Công Nguyên", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H05-076", "name"=>"Trần Thị Mỹ Linh", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H06-077", "name"=>"Đoàn Long An", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"H07-078", "name"=>"Huỳnh Minh Tuấn", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"H08-079", "name"=>"Nguyễn Thị Mai Phương", "faculty"=>"Khoa Khoa học Kỹ thuật thông tin", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"F09-080", "name"=>"Đinh Thanh Toàn", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F10-081", "name"=>"Nguyễn Nhật Hùng", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F11-082", "name"=>"Võ Minh Thiện", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"F12-083", "name"=>"Đặng Quốc Quy", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"F13-084", "name"=>"Huỳnh Ngọc Trân", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"F14-085", "name"=>"Lê Nguyễn Kỳ Duyên", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"F15-086", "name"=>"Nguyễn Hoàng Phúc", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G09-087", "name"=>"Nguyễn Khắc An Dương", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G10-088", "name"=>"Nguyễn Thanh Tú", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G11-089", "name"=>"Nguyễn Tri Đức Anh", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G12-090", "name"=>"Phạm Duy Giác Nguyên", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G13-091", "name"=>"Phạm Tiến Trung", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G14-092", "name"=>"Phan Thị Kim Khoa", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"G15-093", "name"=>"Trần Tấn Đạt", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H09-094", "name"=>"Trần Việt Hùng", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"H10-095", "name"=>"Nguyễn Huỳnh Anh", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"H11-096", "name"=>"Phạm Hoàng Oanh", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"H12-097", "name"=>"Trần Quốc Phong", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"H13-098", "name"=>"Trịnh Ngọc Hiếu", "faculty"=>"Khoa Khoa học Máy tính", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"I09-123", "name"=>"Huỳnh Hồ Thị Mộng Trinh", "faculty"=>"Cán bộ trẻ", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I10-124", "name"=>"Lê Đức Thịnh", "faculty"=>"Cán bộ trẻ", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I11-125", "name"=>"Trần Hoàng Lộc", "faculty"=>"Cán bộ trẻ", "group"=> 2, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I12-126", "name"=>"Lý Trọng Nhân", "faculty"=>"Cán bộ trẻ", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I13-127", "name"=>"Võ Tấn Khoa", "faculty"=>"Cán bộ trẻ", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"I14-128", "name"=>"Nguyễn Ngọc Khánh", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"I15-129", "name"=>"Dương Thanh Tùng", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J09-130", "name"=>"Lê Quang Nhật", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J10-131", "name"=>"Lý Hồng Phong", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J11-132", "name"=>"Ngô Quốc Nhu", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J12-133", "name"=>"Nguyễn Lương Duy Khánh", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J13-134", "name"=>"Nguyễn Thành Danh", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J14-135", "name"=>"Nguyễn Trung Hậu", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"J15-136", "name"=>"Phan Thùy Linh", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K09-137", "name"=>"Phùng Văn Hảo", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K10-138", "name"=>"Trần Doãn Minh", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K11-139", "name"=>"Trịnh Minh Toàn", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K12-140", "name"=>"Vũ Thị Hồng Nhung", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"K13-141", "name"=>"Lê Chí Bảo", "faculty"=>"Khoa Kỹ thuật Máy tính", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"B1-001", "name"=>"Nguyễn Hồng Sơn", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"B2-002", "name"=>"Văn Thiên Luân", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB ĐN", "active"=> 1],
            ["id"=>"B3-003", "name"=>"Đặng Đức Châu", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B4-004", "name"=>"Đặng Hồng Quang", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B5-005", "name"=>"Đinh Thanh Tùng", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B6-006", "name"=>"Đỗ Hồng Minh", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B7-007", "name"=>"Đoàn Thanh Phương", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"B8-008", "name"=>"Hồ Xuân Nghĩa", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C1-009", "name"=>"Huỳnh Thị Ánh Tuyết", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C2-010", "name"=>"Lê Đăng Dũng", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C3-011", "name"=>"Lê Thanh Hồng Nhựt", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C4-012", "name"=>"Lê Thị Huyền Thư", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C5-013", "name"=>"Nguyễn Dương Bá Phú", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C6-014", "name"=>"Nguyễn Hoàng Phúc", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C7-015", "name"=>"Nguyễn Thanh Thảo", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"C8-016", "name"=>"Nguyễn Trí Tâm", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D1-017", "name"=>"Phạm Ngọc Tâm", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D2-018", "name"=>"Phạm Thị Phương Anh", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D3-019", "name"=>"Phan Trung Phát", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 2, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D4-020", "name"=>"Tạ Nguyễn Chung Tín", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D05-021", "name"=>"Trần Chí Thiện", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D06-022", "name"=>"Trần Quang Đạo", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D07-023", "name"=>"Trần Văn Như Ý", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"D08-024", "name"=>"Vũ Anh Hào", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB CT", "active"=> 1],
            ["id"=>"E01-025", "name"=>"Châu Thị Nguyệt", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E02-026", "name"=>"Lâm Nguyễn Hồng Thành", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E03-027", "name"=>"Lương Quốc Bảo", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E04-028", "name"=>"Nguyễn Trần Hùng Vĩ", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 3, "type"=> "ĐB DK", "active"=> 0],
            ["id"=>"E05-029", "name"=>"Phan Đặng Trúc Quyên", "faculty"=>"Khoa Mạng máy tính và truyền thông", "group"=> 1, "type"=> "ĐB DK", "active"=> 0],
         ]);
    }
}
